config/routes.rb
Rails.application.routes.draw do
  
  root "sessions#landing"

  

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'login', to: "sessions#login", as: "login"
  get 'signup', to: "sessions#signup", as: "signup"
  get 'search', to: "users#search", as: "search"
  post 'login', to: "sessions#attempt_login"
  delete 'logout', to: "sessions#logout", as: "logout"
  post 'match/:id', to: "users#match", as: "match"
  post 'matched/:id', to: "users#add_match", as: "add_match"
  delete 'match/:id', to: "users#no_match", as: "no_match"
  delete 'matched/:id', to: "users#remove_match", as: "remove_match"
  

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users, except: [:new]

  resources :kudos, except: [:show, :edit, :update]

  resources :coupons, except: [:show, :edit, :update]

  get 'buy-coupon/:id', to: "coupons#buy", as:"buy_coupon"
  delete 'redeem-coupon/:id', to: "coupons#redeem", as:"redeem_coupon"

end

  #   end

app/models/kudo.rb
class Kudo < ActiveRecord::Base
	validates :description, :points, presence: true
	validates :points, numericality: { greater_than_or_equal_to: 1 }
	has_many :users, through: :accolades
	has_many :accolades, dependent: :destroy

# --------------------------------------------------

 def self.recent_kudos(current_user)
  	@recent_kudos_given = []
    @recent_kudos_given = current_user.kudos.order("created_at DESC").take(6)
 end

# --------------------------------------------------



# --------------------------------------------------

end

app/controllers/kudos_controller.rb
class KudosController < ApplicationController
  
  before_action :confirm_logged_in
  before_action :unmatched_user, except: [:create]
  before_action :set_user, only: [:create, :destroy, :index]
  before_action :set_match, only: [:create, :destroy, :index]

 # ---------------------------------------------

  def index
    @user_created_coupons = @user.coupons.where("creator_id = '#{@user.id.to_s}'")
    @match_created_coupons = @match_user.coupons.where("creator_id = '#{@match_user.id.to_s}'")
  end

    # ---------------------------------------------

  def new
  	@kudo = Kudo.new
  end

    # ---------------------------------------------

    def create


     @kudo = Kudo.new kudo_params  

     @kudo.creator_id = @user.id 
     @kudo.creator_name = @user.name

     # For mailer:
      match = User.find @current_user.match_id
      kudo = @kudo

     if @kudo.save
     # @user.kudos << @kudo
 		 @match_user.kudos << @kudo
     @match_user.score += @kudo.points
     @match_user.save
     # binding.pry
     
     # Uncomment out to send Kudo given emails!
     Give.give_notification(match,kudo).deliver_now

     redirect_to user_path(@current_user), flash: {success: "Kudo Given, Nice!"}
     
         else
 
         render "kudos/new"

     end	
  
    end


# --------------------------------------------- 


def destroy
  

@kudo = Kudo.find params[:id]

if @kudo.destroy
# eventually remove point reduction...
@match_user.score -= @kudo.points
@match_user.save

redirect_to user_path(@current_user), flash: {success: "Kudo Deleted!"}
else
   render "users/show"
end
end



# --------------------------------------------- 


  private

 def set_user
    @user = User.find @current_user.id
 end

 def set_match
    @user = User.find @current_user.id
    @match_user = User.find @user.match_id
 end

 def unmatched_user
      user = User.find_by_id(@current_user.id)
      unless user.match_id
        redirect_to user_path(@current_user.id), alert: "You need a match first"
      end
 end

  def kudo_params
    params.require(:kudo).permit(
      :description,
      :points,
      :picture, 
      :date
    )
  end



end

app/helpers/kudos_helper.rb
module KudosHelper
end

app/views/kudos/index.html.erb
<div class="container margin_top">


<!-- Row One User Kudos -->

<% if @user.kudos.length > 0 %>

<div class="row">
  
<p class="font_lg pad-l-5"><u>My Kudos:</u></p>

<% @user.kudos.each do |kudo|%>

<div class="col-md-6">
 <div class="kudo-box animated fadeInUpBig">
 	
<div class="kudo-box-points">
<p><strong><u>Points:</u></strong></p>
<h1 class="pad-md"><%= kudo.points %></h1>	
</div>
<% if kudo.date %>
<p><strong>Date:</strong> <%= kudo.date.strftime("%m/%d/%Y") %></p>
<% end %>
<p class="text-center font_md pad-md"><%= kudo.description %></p>

 </div>
</div>
<% end %>

</div>  

<% end %>



<!-- Row Two User Coupons -->

<div class="row">

<% if @user_created_coupons.length > 0 %>

<p class="font_lg pad-l-5"><u>My Coupons:</u></p>

<% @user_created_coupons.each do |coupon|%>

<div class="col-md-6">
<div id="coupon" class="design_<%= coupon.design_id %> img-rounded animated fadeInUpBig margin_around">
	
	<p class="coup-head font_resp">PRICE: <strong><%= coupon.price %></strong> points</p>

	<p class="coup-text"><%= coupon.description %></p>


</div>
</div>

<% end %>
<% end %>
</div> 


  
<!-- Row Three Match Kudos -->

<div class="row">

<% if @match_user.kudos.length > 0 %>

<p class="font_main font_resp pad-l-5"><u><%= @match_user.name%>'s Kudos:</u></p>


<% @match_user.kudos.each do |kudo|%>

<div class="col-md-6">
 <div class="kudo-box animated fadeInUpBig">
 	
<div class="kudo-box-points">
<p><strong><u>Points:</u></strong></p>
<h1 class="pad-md"><%= kudo.points %></h1>	
</div>
<% if kudo.date %>
<p><strong>Date:</strong> <%= kudo.date.strftime("%m/%d/%Y") %></p>
<% end %>
<p class="text-center font_md pad-md"><%= kudo.description %></p>


 </div>
</div>
<% end %>
<% end %>
</div>



  
<!-- Row Four Match Coupons -->

<div class="row">

<% if @match_created_coupons.length > 0 %>

<p class="font_main font_resp pad-l-5"><u><%= @match_user.name%>'s Coupons:</u></p>

<% @match_created_coupons.each do |coupon|%>

<div class="col-md-6">
<div id="coupon" class="design_<%= coupon.design_id %> img-rounded animated fadeInUpBig margin_around">
	
	<p class="coup-head font_resp">PRICE: <strong><%= coupon.price %></strong> points</p>

	<p class="coup-text pad-bottom-sm"><%= coupon.description %></p>

	<!-- Only have the option to buy if the user has enough points -->
	<% if @user.score > coupon.price %>

	<p><%= link_to "", buy_coupon_path(coupon), { :style=>'color:#FFFFFF;', :class=>'fa fa-cart-plus fa-3x' } %></p>
    
    <% end %>

</div>
</div>

<% end %>
<% end %>
</div>




</div> <!-- end -->

app/views/kudos/new.html.erb
<div class="container kudo_form margin_top">

<%= render partial: "shared/errors", locals:{instance: @kudo} %>


  <%= form_for @kudo, url: kudos_path do |f| %>
       
        <div class="form-group">
          <%= f.label :description, class:"control-label" %>
          <%= f.text_area :description, size: "24x4", class:"form-control" %>
        </div>
        <div class="form-inline">
        <div class="form-group">
          <%= f.label :points, class:"control-label" %>
          <%= f.number_field :points, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :date, class:"control-label" %>
          <%= f.date_field :date, class:"form-control" %>
        </div>
        </div>
        <br>
        <%= f.submit "Create", id:"submit-user", class:"btn btn-block btn-success text-center" %>
      <% end %>

</div>