config/routes.rb
Rails.application.routes.draw do
  
  root "sessions#landing"

  

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'login', to: "sessions#login", as: "login"
  get 'signup', to: "sessions#signup", as: "signup"
  get 'search', to: "users#search", as: "search"
  post 'login', to: "sessions#attempt_login"
  delete 'logout', to: "sessions#logout", as: "logout"
  post 'match/:id', to: "users#match", as: "match"
  post 'matched/:id', to: "users#add_match", as: "add_match"
  delete 'match/:id', to: "users#no_match", as: "no_match"
  delete 'matched/:id', to: "users#remove_match", as: "remove_match"
  

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users, except: [:new]

  resources :kudos, except: [:show, :edit, :update]

  resources :coupons, except: [:show, :edit, :update]

  get 'buy-coupon/:id', to: "coupons#buy", as:"buy_coupon"
  delete 'redeem-coupon/:id', to: "coupons#redeem", as:"redeem_coupon"

end

  #   end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
	validates :name, presence: true
	has_many :coupons, through: :connections
	has_many :connections, dependent: :destroy
	has_many :kudos, through: :accolades
	has_many :accolades, dependent: :destroy

	has_secure_password


# ---------------------------------------------

  def generate_password_reset_token!
    update(password_reset_token: SecureRandom.urlsafe_base64(48))
  end

# ---------------------------------------------

# Login action for FB Omniauth:

def self.from_omniauth(auth)
    # where(user_params.slice(user_params[:provider], user_params[:uid])).first_or_initialize.tap do |user|

      where(name: auth.info.name).first_or_create do |user|     
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = "Please add email!"
      user.password = auth.uid
      user.picture = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
      # user.provider = user_params.provider
      # user.uid = user_params.uid
      # user.name = user_params.info.name
      # user.oauth_token = user_params.credentials.token
      # user.oauth_expires_at = Time.at(user_params.credentials.expires_at)
      # user.save!
    end
end


# ---------------------------------------------

  private

  def user_params
    params.require(:user).permit(
      :name,
      :password,
      :picture, 
      :email,
      :provider,
      :uid,
      :oauth_token,
      :oauth_expires_at
    )
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
before_action :confirm_logged_in, except: [:create]
before_action :ensure_correct_user, except: [:create, :index, :match, :destroy, :search]
before_action :set_user, only: [:edit, :update, :destroy, :show, :remove_match]
before_action :unmatched_user, only: [:index]
before_action :find_match, only: [:add_match, :no_match, :destroy, :remove_match, :show]

# ---------------------------------------------

  def index
    @all_users = User.all

  end

# ---------------------------------------------

  def search
  
  # binding.pry
    
@found_user = User.find_by(name: params[:name])

if @found_user    
     render "users/index"
    else
     redirect_to users_path, flash: {alert: "No Users Found by that Name!"}
end



  end

# ---------------------------------------------

  def match 
  # finds the user to request a match from
  @match_user = User.find params[:id]
  @match_user.match_request = @current_user.id
  # finds the user to request a match from db and sets match_pending to true
  @user = User.find_by_id(@current_user.id)
  @user.match_pending = true

   if @match_user.save && @user.save
      # binding.pry
      redirect_to user_path(@current_user), flash: {success: "Match request sent!"}
    else
      render "users/index"
   end

  end

# ---------------------------------------------
  
  def add_match 

  # @match_user = User.find_by_id(@current_user.match_request)  
  # Current User in db accepting request
  @user = User.find params[:id]
  @user.match = @match_user.name
  @user.match_id = @match_user.id
  @user.match_request = nil
  @user.match_pending = false

  @match_user.match = @user.name
  @match_user.match_id = @user.id
  @match_user.match_request = nil
  @match_user.match_pending = false

  if @user.save && @match_user.save
      # binding.pry
      redirect_to user_path(@current_user), flash: {success: "Matched with #{@match_user.name}!"}
    else
      render "users/show"
  end

  end

# ---------------------------------------------

  def no_match 
  
  # @match_user = User.find_by_id(@current_user.match_request)  
  # Current User in db accepting request
  @user = User.find params[:id]
  @user.match_request = nil
  @user.match_pending = false

  @match_user.match_request = nil
  @match_user.match_pending = false

  if @user.save && @match_user.save
      # binding.pry
      redirect_to user_path(@current_user), flash: {alert: "Match request declined"}
    else
      render "users/show"
  end

  end

# ---------------------------------------------

  def remove_match

          @match_user.kudos = []
          @match_user.match_request = nil
          @match_user.match_pending = false
          @match_user.match = nil
          @match_user.match_id = nil
          @match_user.score = 0
          
          @user.kudos = []
          @user.match_request = nil
          @user.match_pending = false
          @user.match = nil
          @user.match_id = nil
          @user.score = 0
         if @user.save && @match_user.save

          redirect_to user_path(@current_user), flash: {alert: "Match removed!"}
         else
       
         render :edit

         end

    

  end

# ---------------------------------------------

  def show

      @all_users = User.all
      @recent_kudos = Kudo.recent_kudos(@current_user)
      
      # Need to add conditional statement for (if) @current_user.match
      if @current_user.match
      # Finds match info for the user show page
      @match_bought_coupons = @match_user.coupons.where("creator_id != '#{@match_user.id.to_s}'")
      end

      @user_bought_coupons = @user.coupons.where("creator_id != '#{@user.id.to_s}'")
      # finds all the coupons associated with the user that do not have the user's 
      # id as its creator_id....  

      if @current_user.match_request
      @match_user = User.find_by_id(@current_user.match_request)  
      elsif @current_user.match
      @match_user = User.find_by_id(@current_user.match_id)  
      end

     # binding.pry

  end

# ---------------------------------------------

  def edit
  end

# ---------------------------------------------

 def update

   @user.update user_params

   # Re-saves user's name to match in case that was updated, match 
   # holds user's name in its Active Record Object: 

  if @user.match     
   match_user = User.find_by_id(@user.match_id)
   match_user.match = @user.name
   match_user.save
  end

   if @user.save
      redirect_to user_path(@current_user), flash: {success: "Information updated!"}
    else
      render :edit
   end
 end

# ---------------------------------------------



  def destroy

    # @user = User.find params[:id]
    
    if @user.id === @current_user.id
       
       if @user.destroy
          session[:user_id] = nil
          @match_user.kudos = []
          @match_user.match_request = nil
          @match_user.match_pending = false
          @match_user.match = nil
          @match_user.match_id = nil
          @match_user.score = 0
          @match_user.save

          redirect_to root_path, flash: {alert: "User Account Deleted!"}
       else
          render "users/show"
       end

    else
       if @user.destroy
          redirect_to user_path(@current_user), flash: {alert: "User Deleted!"}
       else
          render "users/show"
       end
    end
  end

# ---------------------------------------------

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      @landing_page = true
      render "sessions/signup"
    end
  end

# --------------------------------------------- 

  private

 def set_user
    @user = User.find params[:id]
 end

  def user_params
    params.require(:user).permit(
      :name,
      :password,
      :picture, 
      :email
    )
  end

  def ensure_correct_user
      user = User.find params[:id]
      unless user.id.to_i == current_user.id
        redirect_to login_path, alert: "Not Authorized"
      end
  end

  def unmatched_user
      user = User.find_by_id(@current_user.id)
      unless user.match_pending == false && !user.match_id
        redirect_to user_path(@current_user.id), alert: "You are already matched or have a match pending"
      end
  end

 def find_match
      if @current_user.match_id === nil
      @match_user = User.find_by_id(@current_user.match_request)  
      else
      @match_user = User.find_by_id(@current_user.match_id)  
      end
 end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container edit_user_form margin_top">

     <h2 class="text-center font_lg"><u>Edit your information:</u></h2><br>

      <%= render partial: "shared/errors", locals:{instance: @user} %>
      
      <%= form_for @user, url: user_path(@user) do |f| %>
       
        <div class="form-group">
          <%= f.label :name, class:"control-label" %>
          <%= f.text_field :name, class:"form-control" %>
          <p class="help-block">* If you are going to use Facebook login please make sure your name matches what is shown in Facebook.</p>
        </div>
           <div class="form-group">
          <%= f.label :email, class:"control-label" %>
          <%= f.email_field :email, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :picture, class:"control-label pad-sm-r" %>

        <!-- Add user options for uploading / editing pictures to Uploadcare here -->

          <%= f.uploadcare_field :picture, class:"form-control", :data => {:crop => '100x100', :"images-only" => 'true'} %>

          <p class="help-block">* Pictures can ONLY be uploaded or edited via Uploadcare, if you haven’t uploaded an image yet click “Choose an image”, otherwise click the image link or “Choose an image” to update your current picture.</p>

        </div>

        <%= f.submit "Update My Account", id:"submit-user", class:"btn btn-block btn-success text-center" %>
      <% end %>
   <br>
   <%= link_to "Reset My Password", new_reset_path, class:"btn btn-block btn-info" %>
  
   
   <% if @user.match_id != nil %>
   <br>
   <%= link_to "Remove My Match", remove_match_path(@user.id), method: :delete, class:"btn btn-block btn-warning", data: {confirm: "Are you sure? This will delete all of your shared information with your match!"} %>

    <% end %>

   <br>
   <%= link_to "Delete My Account", user_path(@user.id), method: :delete, class:"btn btn-block btn-danger", data: {confirm: "Are you sure? This will delete all of your information and that shared with your match!"} %>
</div>

app/views/users/index.html.erb
<div class="all-user-box margin_top container">
<%= render partial: 'shared/alerts' %>
<h2 class="white text-center font_lg"><u>Availible Matches</u></h2>
		
	<% if @all_users %>

		<% @all_users.each do |user|%>

			<% if user.match == nil && user.name != @current_user.name %>

				<div class="col-md-6">

				<h4 class="white text-left">

				<% if user.picture %>
				<%= image_tag("#{user.picture}", id:"profile-img-admin", class:"img-rounded", alt:"") %>
				<% end %>

				<%= user.name%> / <%= link_to "Match", match_path(user.id), method: :post %></h4>

				</div>
		    <% end %>
		<% end %>

	<% elsif @found_user.match == nil && @found_user.name != @current_user.name %>

         <div class="col-md-6">

			<h3 class="white text-left">

			<% if @found_user.picture %>
			<%= image_tag("#{@found_user.picture}", id:"profile-img-admin", class:"img-rounded") %>
			<% end %>

			<%= @found_user.name%> / <%= link_to "Match", match_path(@found_user.id), method: :post %></h3>

	    </div>

    <% else %>

	<h3 class="white text-center font_md">This User already has a Match, Sorry!</h3>

	<% end %>


</div>



<!-- search box for Users to look for a specific name -->
<div class="text-center search-box">

<div class="form-group">
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:name, "Search by Name:", class:"control-label font_md") %>
  <%= text_field_tag(:name, "", class:"form-control") %>
  </div>
  <%= submit_tag("Search", class:"btn btn-block btn-primary") %>
<% end %>

<br>

<!-- resets the page -->
<%= link_to "See All Users", users_path, class:"btn btn-block btn-info" %>

</div>



<!-- help copy -->
<p class="help-block font_md notes_below text-center"><strong>Help:</strong> Matches are listed by Name so you need to know your Matches Account Name (case sensitive) in order to find them. If you do not see your Matches name listed then that means they do not have an account and need to Sign Up!</p>

app/views/users/show.html.erb
<div class="container margin_top">
	
<div class="row">

 <%= render partial: 'shared/alerts' %>
  
<!-- Column One -->

<div class="col-md-6">

<% if current_user.picture == "" %>

     <div class="text-center"><%= link_to "Add a Picture!", edit_user_path(current_user), class:"font_lg white" %></div>

<!-- Removed show user photo logic -->

<% end %>


<h1 class="text-center font_lg">Your Score: </h1>

<h1 class="text-center num_xl"><strong><%= current_user.score %></strong></h1>

</div>



<!-- Column Two -->

<div class="col-md-6">

<!-- Logic checking if the user entered a valid email -->

<% if current_user.email === "Please add email!" %>

<div class="text-center"><%= link_to "Please add email!", edit_user_path(@current_user), class:"font_lg" %></div>

<% end %>


<!-- Logic for Showing Match Status -->

<% if current_user.match != nil %>

<!-- Has Match Logic -->

	
<h1 class="text-center font_lg">Match:</h1>


<h1 class="text-center font_main font_resp">

<% if @match_user.picture %>

<%= image_tag("#{@match_user.picture}", id:"profile-img-match", class:"img-rounded", alt:"") %>

<% end %>

<%= current_user.match %>
	
</h1>


<p class="text-center font_lg"><%= link_to "Give a Kudo", new_kudo_path %></p>


<!-- End has Match Logic -->




<% elsif current_user.match_pending or current_user.match_request %>

<h1 class="text-center font_lg">Match: Request Pending!</h1>

<% else %>

<h1 class="text-center font_lg">Match: <%= link_to "Find One!", users_path %></h1>

<% end %>



</div>

</div>



<!-- Row Two -->

<div class="row">

<div class="col-md-6">

<!-- Match Details -->
<% if current_user.match %>
<div class="match-details-box">
	
<h1 class="white text-center font_lg"><u>My Match:</u></h1>

<h3 class="white text-center">Email: <%= @match_user.email %></h3>

<h3 class="white text-center">Score: <%= @match_user.score %></h3>

<h3 class="white text-center">Kudos: <%= @user.kudos.length %></h3>

<h3 class="white text-center">Coupons Bought: <%= @match_bought_coupons.length %></h3>

</div>

<% end %>

<!-- End Match Details -->

</div>





<div class="col-md-6">

<!-- Logic for accepting/declining match request -->

<% if current_user.match_request %>

<h1 class="text-center"><%= image_tag("#{@match_user.picture}", id:"profile-img", class:"img-rounded img-responsive box_align") %> You have a pending match request from <span class="white"><%= @match_user.name%></span></h1>

<h1 class="text-center"><%= link_to "Accept", add_match_path(@current_user.id), method: :post %> / <%= link_to "Decline", no_match_path(@current_user.id), method: :delete %></h1>


<% end %>

<!-- end pending match request -->

 <% if @match_user %>

<div class="match-details-box mobile_margin">

<p class="white text-center font_md"><u>kudos you have given:</u></p>	

<% @match_user.kudos.reverse_each do |kudo| %>
<% if kudo.creator_id.to_i == @user.id %>
<div class="kudo-box-created">
<% if kudo.date %>
<p><strong>Date:</strong> <%= kudo.date.strftime("%m/%d/%Y") %></p>
<% end %>
<p class="text-center font_sm"><%= kudo.description %></p>
<p class="text-center">Points: <strong><%= kudo.points %></strong> / <%= link_to "Delete", kudo_path(kudo), method: :delete %></p>

</div>
<% end %>
<% end %>

	</div>

<% end %>


</div>

</div>




<!-- Row Three -->

<br>
<div class="row">

<% if @user_bought_coupons.length > 0 %>

<p class="font_main font_resp pad-l-5"><u>Coupons to be Redeemed:</u></p>

<% @user_bought_coupons.each do |coupon|%>

<div class="col-md-6">

<div id="coupon" class="design_<%= coupon.design_id %> img-rounded animated fadeInUpBig margin_around">
	
	<p class="coup-head font_resp">PRICE: <strong><%= coupon.price %></strong> points</p>

	<p class="coup-text pad-bottom-sm"><strong>I get:</strong> <%= coupon.description %></p>


<!-- Coupon Redeem -->

<p class="coup-text"><strong><i class="fa fa-paper-plane"></i> <%= link_to "Use!", redeem_coupon_path(coupon), { method: :delete, :style=>'color:#FFFFFF;' } %></strong></p>

</div>
</div>

<% end %>
<% end%>
</div>




<!-- Row Four -->
<br>
<div class="row">

<% if @recent_kudos.length > 0 %>

<p class="font_main font_resp pad-l-5"><u>Kudos Received:</u></p>

<% @recent_kudos.reverse_each do |kudo|%>

<div class="col-md-6">
 <div class="kudo-box animated fadeInUpBig">
 	
<div class="kudo-box-points">
<p><strong><u>Points:</u></strong></p>
<h1 class="pad-md"><%= kudo.points %></h1>	
</div>
<% if kudo.date %>
<p><strong>Date:</strong> <%= kudo.date.strftime("%m/%d/%Y") %></p>
<% end %>
<p class="text-center font_md pad-md"><%= kudo.description %></p>




 </div>
</div>
<% end %>
<% end%>
</div>






<!-- Logic for editing all users if current user is admin -->

<% if current_user.is_admin %>

	<div class="match-details-box">
		
		<h1 class="white text-center font_main font_resp"><u>Admin</u>: (all users)</h1>

		<% @all_users.each do |user|%>

			<!-- Removes current admins from the admin box -->

			<% if !user.is_admin %>

				<div class="col-md-6">

					<h4 class="white text-left">

					<% if user.picture %>

					<%= image_tag("#{user.picture}", id:"profile-img-admin", class:"img-rounded", alt:"") %>

					<% end %>

					<%= user.name %> / <%= link_to "Delete", user_path(user.id), method: :delete %></h4>

				</div>
			
			<% end %>
		
		<% end %>

	</div>

<% end %>


<!-- End Container -->

</div>