config/routes.rb
Rails.application.routes.draw do
  
  root "sessions#landing"

  

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'login', to: "sessions#login", as: "login"
  get 'signup', to: "sessions#signup", as: "signup"
  get 'search', to: "users#search", as: "search"
  post 'login', to: "sessions#attempt_login"
  delete 'logout', to: "sessions#logout", as: "logout"
  post 'match/:id', to: "users#match", as: "match"
  post 'matched/:id', to: "users#add_match", as: "add_match"
  delete 'match/:id', to: "users#no_match", as: "no_match"
  delete 'matched/:id', to: "users#remove_match", as: "remove_match"
  

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users, except: [:new]

  resources :kudos, except: [:show, :edit, :update]

  resources :coupons, except: [:show, :edit, :update]

  get 'buy-coupon/:id', to: "coupons#buy", as:"buy_coupon"
  delete 'redeem-coupon/:id', to: "coupons#redeem", as:"redeem_coupon"

end

  #   end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
	validates :description, :price, presence: true
	has_many :users, through: :connections
	has_many :connections, dependent: :destroy
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  
before_action :confirm_logged_in
before_action :set_user, only: [:create, :destroy, :index]

  def index

      @user_created_coupons = @user.coupons.where("creator_id = '#{@user.id.to_s}'")
      # finds all the coupons associated with the user that have the user's id as its
      # creator_id....

  end

  # ---------------------------------------------

  def new
      @coupon = Coupon.new
  end

   # ---------------------------------------------

  def create
     
     @coupon = Coupon.new coupon_params  

     @coupon.creator_id = @user.id 
     @coupon.creator_name = @user.name

     if @coupon.save

      @user.coupons << @coupon
  
     redirect_to user_path(@current_user), flash: {success: "Coupon Created!"}
     
         else
 
         render "coupons/new"

     end

  end


# ---------------------------------------------

def buy  

    # assigns the coupon being bought to a variable
    coupon = Coupon.find params[:id]
    # @coupon = Coupon.find params[:id]

       # creates a duplicate of the Active Record Object and assigns it to an 
       # instance variable.
       @coupon = coupon.dup

    # assigns the new object (coupon) to the match
    @current_user.coupons << @coupon
    @current_user.score -= @coupon.price
    @current_user.save

    redirect_to user_path(@current_user), flash: {success: "Coupon Bought!"}

end

# --------------------------------------------

def redeem 

@coupon = Coupon.find params[:id]

# For mailer:
match = User.find @current_user.match_id
coupon = @coupon

# Need to destroy coupon and send email to match_user

if @coupon.destroy

@current_user.save

# Uncomment out to send Coupon Redeemed Emails!
Redeem.redeem_notification(match,coupon).deliver_now

redirect_to user_path(@current_user), flash: {success: "Coupon Used!"}

else

   render "users/show"
end

end

# --------------------------------------------


def destroy 

@coupon = Coupon.find params[:id]

if @coupon.destroy

@user.save

redirect_to user_path(@current_user), flash: {success: "Coupon Deleted!"}
else
   render "users/show"
end
end


# --------------------------------------------- 


  private

 def set_user
    @user = User.find @current_user.id
 end

  def coupon_params
    params.require(:coupon).permit(
      :description,
      :price,
      :design_id
    )
  end


  
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/index.html.erb
<div class="container margin_top">

<div class="row">

<% if @user_created_coupons.length > 0 %>

<p class="font_lg pad-l-5"><u>My Coupons:</u></p>

<% @user_created_coupons.each do |coupon|%>

<div class="col-md-6">
<div id="coupon" class="design_<%= coupon.design_id %> img-rounded animated fadeInUpBig margin_around">
	
	<p class="coup-head font_resp">PRICE: <strong><%= coupon.price %></strong> points</p>

	<p class="coup-text pad-bottom-sm"><%= coupon.description %></p>

<p class="coup-text"><%= link_to "", coupon_path(coupon), { method: :delete, :style=>'color:#FFFFFF;', :class=>'fa fa-trash fa-2x' } %></p>

</div>
</div>

<% end %>
<% end%>
</div>


</div>

app/views/coupons/new.html.erb
<div class="container coupon_form margin_top">

<%= render partial: "shared/errors", locals:{instance: @coupon} %>

  <%= form_for @coupon, url: coupons_path do |f| %>
       
        <div class="form-group">
          <%= f.label :description, class:"control-label" %>
          <%= f.text_area :description, size: "24x4", class:"form-control" %>
        </div>
        <div class="form-inline">
        <div class="form-group">
          <%= f.label :price, class:"control-label" %>
          <%= f.number_field :price, class:"form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :design_id, class:"control-label" %>
          <%= f.select :design_id, [["One", 1], ["Two", 2], ["Three", 3], ["Four", 4]], class:"form-control" %>
        </div>
        </div>
        <br>
        <%= f.submit "Create", id:"submit-user", class:"btn btn-block btn-success text-center" %>
      <% end %>

</div>

<!-- End of Create Coupon Form -->

<br>

<!-- Coupon Options -->

<div class="container">

<h1>Coupon Design Options</h1>


<div class="row">

<div class="col-md-6">

<h3>Design 1:</h3>

<div id="coupon" class="design_1 img-rounded">
	
	<p class="coup-head font_resp">PRICE: <strong>5 POINTS</strong></p>

	<p class="coup-text">Voluptate non leberkas, rump frankfurter turkey ham. Kevin tempor jerky, pastrami kielbasa porchetta commodo in capicola ea doner.</p>


</div>


</div>

<div class="col-md-6">

<h3>Design 2:</h3>

<div id="coupon" class="design_2 img-rounded">
	
	<p class="coup-head font_resp">PRICE: <strong>5 POINTS</strong></p>

	<p class="coup-text">Voluptate non leberkas, rump frankfurter turkey ham. Kevin tempor jerky, pastrami kielbasa porchetta commodo in capicola ea doner.</p>


</div>

</div>

</div> <!-- end row one -->

<br>

<div class="row">

<div class="col-md-6">

<h3>Design 3:</h3>

<div id="coupon" class="design_3 img-rounded">
  
  <p class="coup-head font_resp">PRICE: <strong>5 POINTS</strong></p>

  <p class="coup-text">Voluptate non leberkas, rump frankfurter turkey ham. Kevin tempor jerky, pastrami kielbasa porchetta commodo in capicola ea doner.</p>

</div>

</div>

<div class="col-md-6">

<h3>Design 4:</h3>

<div id="coupon" class="design_4 img-rounded">
  
  <p class="coup-head font_resp">PRICE: <strong>5 POINTS</strong></p>

  <p class="coup-text">Voluptate non leberkas, rump frankfurter turkey ham. Kevin tempor jerky, pastrami kielbasa porchetta commodo in capicola ea doner.</p>


</div>


</div>
</div> <!-- end row two -->




</div>