config/routes.rb
Rails.application.routes.draw do
  
  root "sessions#landing"

  

match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
match 'auth/failure', to: redirect('/'), via: [:get, :post]
match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  get 'login', to: "sessions#login", as: "login"
  get 'signup', to: "sessions#signup", as: "signup"
  get 'search', to: "users#search", as: "search"
  post 'login', to: "sessions#attempt_login"
  delete 'logout', to: "sessions#logout", as: "logout"
  post 'match/:id', to: "users#match", as: "match"
  post 'matched/:id', to: "users#add_match", as: "add_match"
  delete 'match/:id', to: "users#no_match", as: "no_match"
  delete 'matched/:id', to: "users#remove_match", as: "remove_match"
  

  resources :resets, only: [:new, :edit, :create, :update]

  resources :users, except: [:new]

  resources :kudos, except: [:show, :edit, :update]

  resources :coupons, except: [:show, :edit, :update]

  get 'buy-coupon/:id', to: "coupons#buy", as:"buy_coupon"
  delete 'redeem-coupon/:id', to: "coupons#redeem", as:"redeem_coupon"

end

  #   end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Me&You</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

<%= render partial: 'shared/theme_header' %>


<!-- Brings in Uploadcare Functionality -->

<%= uploadcare_settings %>


</head>
<body class="<%= @landing_page ? 'flower' : ''%>">

<!-- Custom Navbar -->

 <nav id="mainNav" class="navcolor navbar navbar-default navbar-fixed-top">

<!-- navbar-fixed-top : affects spcaing but makes it fill the space -->

    <div class="container-fluid">



      <div class="navbar-header">


      <!-- navbar-nav : lowers drop down menu -->

<ul class="nav">
    <li class="dropdown">


         <a class="navbar-brand" href="#">
        <%= image_tag("me&you_squarelogo.png", :alt => "Me & You", class:"nav-logo") %>
      </a>
       

     <% if @current_user %>

       <ul class="dropdown-menu pad-drop-down" id="pulled-nav-elements"> 

             <!-- right now the collapse button is pulling this list "#pulled-nav-elements" -->

            <li><strong><u><%= @current_user.email %></u></strong></li>
            <li><%= link_to "My Page", user_path(@current_user) %></li>
            <li><%= link_to "Edit My Account", edit_user_path(@current_user) %></li>
            <li><%= link_to "Our Page", kudos_path %></li>
            <li><%= link_to "Give A Kudo", new_kudo_path %></li>
            <li><%= link_to "Add Coupon", new_coupon_path %></li>
            <li><%= link_to "See My Coupons", coupons_path %></li>
            <li><%= link_to "Log Out", logout_path, {method: :delete}%></li>

        </ul>

      <% end %> 

       <% if !@current_user %>
       <!-- signifies login pages -->

       <ul class="dropdown-menu" id="pulled-nav-elements"> 

             <!-- right now the collapse button is pulling this list "#pulled-nav-elements" -->
             <!-- this list shows if there is not a current user (login/signup) -->

          <li><%= link_to "Email Login", login_path %></li>
          <li><%= link_to "Facebook Login", "/auth/facebook" %></li>
          <li><%= link_to "Sign up here", signup_path %></li>

        </ul>

      <% end %> 
      
    </li>


<!-- placed button inside <ul> so they don't overlap -->

   <button type = "button" class = "navbar-toggle navbar-text navbar-right" data-toggle = "collapse" data-target = "#pulled-nav-elements">

   <!-- can set data-target to the information you want to share -->
         
         <span class = "icon-bar"></span>
         <span class = "icon-bar"></span>
         <span class = "icon-bar"></span>
      </button>
 

  </ul>
     
 </div>



<!-- the class "collapse" triggers an event where content is hidden and collapse is toggled -->

<!-- removed "collapse" from below to work on mobile responsive layout -->

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<!-- snip 2 -->

        <ul class="nav navbar-nav navbar-right">
          <% if @current_user %>
             
               <!-- adds the name of the current user to the global nav -->
               <li class="navbar-text" style="color: white"><%= @current_user.name %></li>

               <% if @current_user.picture != ""%>
             
               <li class="navbar-text"><%= image_tag("#{current_user.picture}", class:"img-rounded avatar", alt:"") %></li>

                <% end %>

           <!-- snip 1 -->

          <% else %>
            <li><%= link_to "Email Login", login_path, {:style => 'color: white', :class => 'text-center'} %> </li>

           <!-- FB Login link -->
           
          <li><%= link_to "Facebook Login", "/auth/facebook", {:style => 'color: white', :class => 'text-center'} %> </li>


          <% end %>
       
        </ul>

      </div>

    </div>

  </nav>

<!--   End Navbar -->

<!--   Flash Message did go here -->

<!-- Page Content -->

<%= yield %>


<!-- End Page Content -->

  <%= render partial: 'shared/footer' %>

  <%= render partial: 'shared/end_javascript' %>

</body>
</html>